version: '3.1'

services:

  database:
    container_name: ponto-database
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ponto
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "./database/sql:/docker-entrypoint-initdb.d/sql"
      - "./database/setup.sh:/docker-entrypoint-initdb.d/setup.sh"

  pgadmin:
    container_name: ponto-pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@email.com
      PGADMIN_DEFAULT_PASSWORD: postgres

volumes:
  postgres_data:
