version: "3.1"

services:
  api-gateway:
    container_name: ponto-api-gateway
    image: nginx
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:z
    ports:
      - "443:443"

  database:
    container_name: ponto-database
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ponto
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "./database/sql:/docker-entrypoint-initdb.d/sql:z"
      - "./database/setup.sh:/docker-entrypoint-initdb.d/setup.sh:z"

  pgadmin:
    container_name: ponto-pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@email.com
      PGADMIN_DEFAULT_PASSWORD: postgres

volumes:
  postgres_data:
