version: '3.1'

services:
  api:
    container_name: ponto-api
    build: ./api
    env_file:
      - ./api/.env
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    container_name: ponto-database
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - ./database/.env
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "./database/sql:/docker-entrypoint-initdb.d/sql:z"
      - "./database/setup.sh:/docker-entrypoint-initdb.d/setup.sh:z"

  pgadmin:
    container_name: ponto-pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    env_file:
      - ./database/.env

volumes:
  postgres_data:
